### PR TITLE
Implement Delete Endpoint In InventoryController & Unit Test

### PR DESCRIPTION
**Pull request by HexagonBen**
Implement Delete Endpoint In InventoryController & Unit Test

I found it strange that Spring returned a 200 status when I attempted to delete a document with a non-existent id. The unit test shows that nothing gets deleted, so I would expect a 404 resource not found response, but Spring returns a 200.

In any case, here is my attempt at Task4.

### CODE REVIEW

**Comment by jdiangelo** [comment]
Knowledge Check:
1) This task can be done with both RequestParams and RequestBody. Why did you choose the method you chose? 
2) Is a String ID or List of String IDs more appropriate for this delete method?

**Comment by jdiangelo** [comment]
Regarding the test with an invalid id - If the id given does not exist, then is there anything to do? What if the id is null or empty string? Will it still give a 200?

**Comment by HexagonBen** [comment]
> Knowledge Check:
> 
**> 1. This task can be done with both RequestParams and RequestBody. Why did you choose the method you chose?**
A quick summary of common conventions based on what I’ve read:
Spring’s @RequestBody corresponds to the request body of the HTTP request (commonly used for POST & PUT requests).
Spring’s @PathVariable corresponds to the path variable (part of the actual url route). This is commonly used for pointing to specific resources (e.g. ids), and is commonly used for GET and DELETE operations.
Spring’s @RequestParam corresponds to query parameters. This is conventionally used mainly for filtering results, like if I wanted to perform a GET operation on our inventories and retrieve only the inventories with a neverExpires property of `true`.

Based on the conventions I’ve read, It would have been very appropriate to use @PathVariable here, but I figured I would keep the code as simple as possible and just do @RequestBody for everything if I could get away with it. Although for all I know my choice to use only the request body will come back to bite me while I’m wiring up the front end. I have my fingers crossed haha.


**> 2. Is a String ID or List of String IDs more appropriate for this delete method?**
I think a List of String IDs might be more appropriate, because that would make it easier to allow the user to select and delete multiple inventories at once if desired from the UI. This could also be accomplished by using a single string id and calling the function multiple times, once for each id, but that would be inefficient.

I think I could use the `findAllAndRemove` mongoTemplate method in the inventoryDAO like this:

    Query query = new Query();
    query.addCriteria(Criteria.where("id").in(listOfIds))
    Inventory deletedInventory = this.mongoTemplate.findAllAndRemove(query, Inventory.class)

I was thinking about trying to implement this, but I wanted to check with you before I do so I don't spend too much time making a bunch of changes if they aren't necessary, because implementing this will require changes to the inventoryController delete method, and its unit test, and the inventoryDAO delete method, and the unit test for the inventoryDAO delete method as well.

Do you think I should make this change, or is the way I have it accepting a single String id better or sufficient?

**Comment by HexagonBen** [comment]
> Regarding the test with an invalid id - If the id given does not exist, then is there anything to do? What if the id is null or empty string? Will it still give a 200?

Makes sense. I did some reading and from what I can tell delete requests never return 404, because if the resource already doesn't exist before the delete request happens, that doesn't reflect a failure; it's still the desired outcome.

From what I've read only GET and PUT requests can return a 404.

**Review by jdiangelo — APPROVED** [review]

**Pull request merged**
